export const devInfo = {
  name: "Black W",
  email: "blackwang104@gmail.com",
  github: "https://github.com/black-2u",
  telegram: "https://t.me/Black_2U",
  whatsapp: "https://wa.me/13202919094",
};

export const star = "Gaurav Sharma";

export const nickname = "Gaurav Sharma";

export const experience = [
  {
    id: 1,
    title: "UI/UX Designer",
    company: "Global Logic",
    location: "Noida",
    period: "Jan 2022 - Present",
    description: [
      "Fostered collaboration and consistency across the teams by working closely with product managers, designer, and engineers",
      "I have actively engaged in UX design and development within the context of a Lab Automation Platform, striving to enhance the overall user experience. Working closely with cross-functional teams, I have successfully implemented user centered design principles tailored to the Lab Automation Platform's unique requirements.",
      "A key aspect of my role involved optimizing user workflows and interactions, streamlining processes to ensure seamless navigation and efficient usability. Through iterative design and usability testing, I have continually worked towards creating an intuitive and user-friendly experience for all platform users.",
      "Contributed to the Metaverse platform intuitive, ensuring seamless onboarding experiences for new employees.",
    ],
  },
  {
    id: 2,
    title: "UX Designer",
    company: "Capgemihi",
    location: "Pune",
    period: "June 2019 - Jan 2022",
    description: [
      "I have experience in defining user experiences and design frameworks for products across diverse sectors, including E-Commerce (B2C), IT Industry (B2B), Computer Technology (B2E), Power and Utility (B2B) and Supply Chain, Inventory & Order Management (B2C).",
      "As the lead UX designer, I spearheaded the design efforts for the IKEA bristro kiosk, taking a user-centric approach throughout the process. Collaborating closely with stakeholders, I conducted in-depth user research to understand the specific needs, preferences, and pain points of customers when interacting with the kiosk.",
    ],
  },
];

export const skillSet = {
  design: [
    "Interview & Survey",
    "Heuristic Evaluation",
    "Competitor Analysis",
    "Persona & User Stories",
    "Strategic Storyboarding",
    "Journey Mapping",
    "Task Flow & User Flow",
    "Pattern Library",
    "Wireframing",
    "Prototyping",
  ],
  tools: [
    { tool: "Adobe XD", icon: "/svg/adobe-xd.svg" },
    { tool: "Adobe Indesign", icon: "/svg/adobe-indesign.svg" },
    { tool: "Sketch", icon: "/svg/sketch.svg" },
    { tool: "Figma", icon: "/svg/figma.svg" },
    { tool: "Invision", icon: "/svg/invision.svg" },
    { tool: "Illustrator", icon: "/svg/illustrator.svg" },
    { tool: "Photoshop", icon: "/svg/photoshop.svg" },
    { tool: "Premiere Pro", icon: "/svg/premiere.svg" },
    { tool: "After Effects", icon: "/svg/after-effects.svg" },
  ],
};

export const projects = [
  {
    id: "1",
    title: "OnboardIT",
    overview:
      "The goal was to design a simple MVP solution to provide a seamless onboarding experience for companies and employees.",
    status: "POC",
    role: "UX Designer",
    tools: ["Adobe XD", "Adobe Illustrator"],
    icons: ["/svg/adobe-xd.svg", "/svg/illustrator.svg"],
    slug: "onboardit",
    url: "https://www.onboardit.com/",
    thumbnail: "/image/project-1.png",
    images: [
      "/image/image-1-1.png",
      "/image/image-1-2.png",
      "/image/image-1-3.png",
      "/image/image-1-4.png",
      "/image/image-1-5.png",
      "/image/image-1-6.png",
      "/image/image-1-7.png",
      "/image/image-1-8.png",
      "/image/image-1-9.png",
    ],
  },
  {
    id: "2",
    title: "Shopsafe",
    overview:
      "Shopsafe is a mobile-based application that helps in managing crowd and take preventive measures in shopping complexes to safeguard visitors and staffs during global pandemics like COVID-19.",
    status: "Design Jam",
    role: "UX Designer",
    tools: ["Adobe XD", "Adobe Illustrator"],
    icons: ["/svg/adobe-xd.svg", "/svg/illustrator.svg"],
    slug: "shopsafe",
    url: "https://www.onboardit.com/",
    thumbnail: "/image/project-2.png",
    images: [
      "/image/image-2-1.png",
      "/image/project-3.png",
      "/image/project-4.png",
      "/image/project-5.png",
      "/image/project-6.png",
      "/image/image-2-2.png",
      "/image/image-2-3.png",
      "/image/image-2-4.png",
      "/image/image-2-5.png",
      "/image/image-2-6.png",
      "/image/image-2-7.png",
      "/image/image-3-1.png",
      "/image/image-3-2.png",
      "/image/image-3-3.png",
      "/image/image-3-4.png",
      "/image/image-4-1.png",
      "/image/image-4-2.png",
      "/image/image-4-3.png",
      "/image/image-4-4.png",
      "/image/image-5-1.png",
      "/image/image-5-2.png",
      "/image/image-5-3.png",
      "/image/image-5-4.png",
      "/image/image-6-1.png",
    ],
  },
  {
    id: "3",
    title: "Verdigreen",
    overview:
      "An augmented reality eCommerce mobile app specifically for indoor plant parents.",
    status: "POC",
    role: "UX Designer",
    tools: ["Adobe XD", "Adobe Illustrator"],
    icons: ["/svg/adobe-xd.svg", "/svg/illustrator.svg"],
    slug: "verdigreen",
    url: "https://www.onboardit.com/",
    thumbnail: "/image/7.png",
    images: [
      "/image/7-1.jpeg",
      "/image/7-2.png",
      "/image/7-3.jpg",
      "/image/7-4.jpg",
      "/image/7-5.jpg",
      "/image/7-6.jpg",
      "/image/7-7.jpg",
      "/image/7-8.jpg",
      "/image/7-9.jpg",
      "/image/7-10.jpg",
      "/image/7-11.png",
    ],
  },
  {
    id: "4",
    title: "Whisker",
    overview:
      "Leading the design of digital products that make life with your pet endlessly better.",
    status: "POC",
    role: "UX/UI Designer, Product Design, Branding",
    tools: ["Adobe XD", "Adobe Illustrator"],
    icons: ["/svg/adobe-xd.svg", "/svg/illustrator.svg"],
    slug: "whisker",
    url: "https://www.onboardit.com/",
    thumbnail: "/image/8.png",
    images: [
      "/image/8-1.png",
      "/image/8-3.png",
      "/image/8-2.png",
      "/image/8-4.png",
      "/image/8-5.png",
    ],
  },
];
